services:
  - type: web
    name: bunyards-coin-stamps
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    domains:
      - bunyardscoins.com
      - www.bunyardscoins.com
